"""
Copyright (c) 2026 MYAIPATHSHALA.com | AITDL.com

Founded by Jawahar Mallah
AI System Architect & Author

Licensed under the MIT License.
See LICENSE file in the project root for full license information.
"""

import os
from typing import Any, Dict, List, Tuple

REQUIRED_SECTIONS = {
    "implementation": [
        "# Implementation Plan:",
        "## User Review Required",
        "## Proposed Changes",
        "## Verification Plan",
        "## Acceptance Criteria"
    ],
    "task": [
        "# AiTDL Task Document:",
        "## Task Breakdown",
        "- [ ]"
    ],
    "walkthrough": [
        "# AiTDL Walkthrough Document:",
        "## Architecture Summary",
        "## Execution Flow",
        "## File-Level Impact",
        "## System Impact"
    ]
}

class StructureValidator:
    """
    Validates the existence and structural integrity of generated documentation.
    Enforces v1.5 STABLE standards.
    """

    def validate_set(self, doc_data: Dict[str, Any]) -> Tuple[bool, str]:
        """
        Validates the in-memory document set generated by the Planner.
        """
        expected_keys = ["implementation", "task", "walkthrough"]
        
        # 1. Check if mandatory documents are present in the 'documents' key
        docs = doc_data.get("documents", {})
        if not all(k in docs for k in expected_keys):
            return False, "Missing mandatory documentation (implementation, task, and walkthrough required)."

        for doc_type, info in docs.items():
            content = info.get("content", "")
            
            # 2. Check if content exists
            if not content.strip():
                return False, f"Document content is empty for: {doc_type}"

            # 3. Check structural integrity
            is_valid, error = self._validate_content(doc_type, content)
            if not is_valid:
                return False, error

        return True, ""

    def _validate_content(self, doc_type: str, content: str) -> Tuple[bool, str]:
        # Check for mandatory headers
        required = REQUIRED_SECTIONS.get(doc_type, [])
        for section in required:
            if section not in content:
                return False, f"Missing required section '{section}' in {doc_type} doc."

        # Special rule for Task doc: No explanation paragraphs
        if doc_type == "task":
            paragraphs = [p for p in content.split("\n\n") if p and not p.strip().startswith("#") and not p.strip().startswith("**") and "- [" not in p]
            
            forbidden_paragraphs = []
            for p in paragraphs:
                p_clean = p.strip()
                if any(x in p_clean for x in ["Copyright", "Jawahar Mallah", "Licensed under", "MIT License"]):
                    continue
                forbidden_paragraphs.append(p_clean)

            if any(len(p.split()) > 10 for p in forbidden_paragraphs):
                 return False, "Task document contains unauthorized explanation paragraphs (v1.5 rules)."

        return True, ""

validator = StructureValidator()
